# Generated by Django 5.1 on 2024-08-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('quantidade_alunos', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('inicio', models.DateTimeField()),
                ('final', models.DateTimeField()),
            ],
        ),
    ]
